---
title: "Analysis 2: Structure and Hybrid Assignment Analysis"
author: "Joe Gunn"
date: "2022-07-28"
output: html_document
---

# Project: Interspecific Hybridization in the Smallmouth Bass species complex : Spotted, Smallmouth, Neosho, Ouachita, and Little River Bass (SNOLH)
<font size="+1">Investigating hybridization and population structure among and within the Spotted Bass (<i>Micropterus punctulatus</i>), Smallmouth Bass (<i>M. dolomieu</i>), the newly elevated Neosho Bass (<i>M. velox</i>), and two other potentially distinct species in the Ouachita River Basin (the Ouachita and Little River Basses)</font>

## Specific Aim: Hierarchical structure analysis with diagnostic markers
For this aim, we are using Bayesian clustering analysis with STRUCTURE to assess patterns and levels of hybridization among and within black bass species in the Interior Highlands, with emphasis on populations in the Arkansas River Basin and Ouachita River Basin. We obtained SNP marker data from from Spotted Bass (<i>M. punctulatus</i>), Smallmouth Bass (<i>M. dolomieu</i>), Neosho Bass (<i>M. velox</i>), and two potentially distinct species in the Ouachita River Basin (Ouachita Bass and Little River Bass) which were known to be diagnostic of these species (Long et al. 2021).

## Phases of Analysis
### Phase 1: Data preparation
### Phase 2: Data summarization
### Phase 3: Structure and hybrid assignment analysis

### Libraries needed for analysis
```{r}
library(tidyverse)
library(cowplot)
library(readxl)
library(writexl)
library(genepopedit)
library(pophelper)
```

## PHASE 1: STRUCTURE AND HYBRID ASSIGNMENT ANALYSIS
Here, we conduct analysis in the software programs STRUCTURE and NEWHYBRIDS in tandem to identify hybrids at multiple hierarchical levels using diagnostic SNPs for the species of interest at each level. We start with analysis of population structure and hybridization in all samples using all SNPs to screen the dataset for any samples not belonging to any of the five species groups (Spotted Bass, Smallmouth Bass, Neosho Bass, Ouachita Bass, and Little River Bass; Step 1a: `01_all_samples_all_snps.Rmd`). Next, we conduct population structure and hybridization analysis on all remaining samples using SNPs that are diagnostic for Spotted Bass and all other Interior Highlands basses, given Spotted Bass as an outgroup (Step 1b: `02_spb_other.Rmd`). Next, we remove Spotted Bass an any hybrids detected in the first analysis, and we conduct population structure and hybridization analysis on remaining samples using SNPs that are diagnostic for Smallmouth Bass and all other Interior Highlands basses, given Smallmouth Bass as an outgroup (Step 1c: `03_smb_ih.Rmd`). Then, we remove Smallmouth Bass and any hybrids detected in the second analysis, and we conduct population structure and hybridization analysis on remaining samples. For this set of samples, we are using all SNPs diagnostic for Neosho Bass, Ouachita Bass, and Little River Bass, and we subset the data into three pairs of sample sets: Neosho Bass and Ouahcita Bass, Neosho Bass and Little River Bass, and Ouachita Bass and Little River Bass, to identify hybrids between each pair of species (Step 1d: `04_ih.Rmd`).

Programs need:

STRUCTURE v.2.3.4. (Pritchard et al. 2000)

Citation:

Pritchard JK, Stephens M, Donnelly P. 2000. Inference of population structure using multilocus genotype data. Genetics 155: 945-959.

CLUMPP v.1.1.2 (Jakobsson and Rosenberg 2007)

Citation:

Jakobsson M, Rosenberg NA. 2007. CLUMPP: A cluster matching and permutation program for dealing with label switching and multimodality in analysis of population structure. Bioinformatics 23: 1801-1806.

We ran each hierarchical analysis in separate .Rmd files, which are found in the `code/` directory.

### STEP 1: Assess all samples with all SNP loci; run the Rmd file: `code/01_all_samples_all_snps.Rmd`
In this step, we are assessing population structure and hybridization between Spotted Bass and all other Interior Highlands species, including Smallmouth Bass, Neosho Bass, Ouachita Bass, and Little River Bass. We use the program STRUCTURE to estimate ancestry coefficients and assess overall population structure among stream populations within the Spotted Bass and Interior Highlands ranges, and then we use NEWHYBRIDS analysis to assign any putative hybrids to one of six hybrid categories (pure parent 1, pure parent 2, F1 hybrid, F2 hybrid, parent 1 back-cross, or parent 2 back-cross). We then omit any detected hybrids from the dataset and continue with population structure and hybridization analysis between Smallmouth Bass and the rest of the Interior Highland species in a hierarchical fashion.

#### STEP 2: Assess Spotted Bass and Interior Highlands species; run the Rmd file: `code/02_spb_other.Rmd`
In this step, we are assessing population structure and hybridization between Spotted Bass and all other Interior Highlands species, including Smallmouth Bass, Neosho Bass, Ouachita Bass, and Little River Bass. We use the program STRUCTURE to estimate ancestry coefficients and assess overall population structure among stream populations within the Spotted Bass and Interior Highlands ranges, and then we use NEWHYBRIDS analysis to assign any putative hybrids to one of six hybrid categories (pure parent 1, pure parent 2, F1 hybrid, F2 hybrid, parent 1 back-cross, or parent 2 back-cross). We then omit any detected hybrids from the dataset and continue with population structure and hybridization analysis between Smallmouth Bass and the rest of the Interior Highland species in a hierarchical fashion.

#### STEP 3: Assess Smallmouth Bass and Interior Highlands species; run the Rmd file: `code/03_smb_ih.Rmd`
In this step, we are assessing population structure and hybridization between Smallmouth Bass and all other Interior Highlands species, including Neosho Bass, Ouachita Bass, and Little River Bass. We use the program STRUCTURE to estimate ancestry coefficients and assess overall population structure among stream populations within the Smallmouth Bass and Interior Highlands ranges, and then we use NEWHYBRIDS analysis to assign any putative hybrids to one of six hybrid categories (pure parent 1, pure parent 2, F1 hybrid, F2 hybrid, parent 1 back-cross, or parent 2 back-cross). We then omit any detected hybrids from the dataset and continue with population structure and hybridization analysis among only the rest of the Interior Highland species in a hierarchical fashion.

#### STEP 4: Assess Interior Highlands species only; run the Rmd file: `code/04_ih.Rmd`
In this step, we are assessing population structure and hybridization between all  Interior Highlands species only, including Neosho Bass, Ouachita Bass, and Little River Bass. We use the program STRUCTURE to estimate ancestry coefficients and assess overall population structure among stream populations within the Smallmouth Bass and Interior Highlands ranges, and then we use NEWHYBRIDS analysis to assign any putative hybrids to one of six hybrid categories (pure parent 1, pure parent 2, F1 hybrid, F2 hybrid, parent 1 back-cross, or parent 2 back-cross).

## ------------------------ END OF ANALYSIS 2: STRUCTURE AND HYBRID ASSIGNMENT ANALYSIS ----------------------- ##

